# Generated by Django 6.0.6 on 2026-06-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='conducted_events',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='club',
            name='upcoming_events',
            field=models.TextField(default=''),
        ),
    ]
